### ISSUE TITLE
jepsen test for crux db

### ISSUE THREAD

**Issue by abdulkaderjeelani** [juxt/crux#1113]
where can we find jepsen test results for crux db ?

**Comment by refset** [comment]
Hi :) Crux is not a _distributed_ database system in a sense that would warrant Crux-specific Jepsen-style analysis of fault-tolerance and/or consensus properties. This is due to how Crux:

1. depends on a singular transaction log
2. doesn't attempt any complex form of clustering or sharding, and
3. only runs single-node queries (unlike, say, Dgraph)

Of course, each storage component within Crux (tx-log, doc-store, index-store) may itself be underpinned by a distributed system. Therefore Jepsen analysis could certainly apply for the _components_ of Crux (e.g. Kafka, Postgres, S3). For instance, here is a very old write-up for Kafka: https://aphyr.com/posts/293-jepsen-kafka

I hope that helps.
