### ISSUE TITLE
When `:where` selects an empty set, no result is returned

### ISSUE THREAD

**Issue by Vaelatern** [juxt/crux#1157]
```
(def node (atom nil))

(defn db-setup [f]
  (reset! node (crux/start-node {}))
  (f)
  (.close @node)
  (reset! node nil))

(use-fixtures :each db-setup)


(deftest empty-set
  (testing "Insert an object with an empty set"
    (crux/await-tx @node (crux/submit-tx @node [[:crux.tx/put {:crux.db/id :TESTING-KEY :a #{}}]]))
    (let [results (crux/q (crux/db @node) '{:find [?e ?a]
                                            :where [[?e :a ?a]]})]
      (is (= 1 (count results))))))
```

Test fails

```
FAIL in (empty-set) (db_test.clj:50)
Insert an object with an empty set
expected: (= 1 (count results))
  actual: (not (= 1 0))
```

This seems quite similar to my previous issue: https://github.com/juxt/crux/issues/882

If the key has an empty set, that's useful knowledge for me. For now I'm able to deactivate that functionality without adverse effects, but it will be important to me later.

**Comment by Vaelatern** [comment]
Really what I'm trying to do is have a :where-not check for a set NOT including a given key.

**Comment by jarohen** [comment]
This is the expected behaviour for sets as values in Crux - the semantics of the document you've specified is that `:TESTING-KEY` doesn't have any outbound `:a` edges, and your query is asking for documents _with_ outbound `:a` edges.

For the case where you want the sets that don't include that keyword, a 'not-join' should work:

```clojure
{:find [k]
 :where [[k :crux.db/id]
         (not-join [k]
                   [k :a :not-this-attribute])]}
```

or, indeed, keys without any attributes:

```clojure
{:find [k]
 :where [[k :crux.db/id]
         (not-join [k]
                   [:k :a])]}
```
