### ISSUE TITLE
General Availability timeline

### ISSUE THREAD

**Issue by esunder** [juxt/crux#824]
Hello,

Is there a roadmap or timeline of the general availability of crux? When would we see a beta or stable version of the database be ready for production use?

If not, what kinds of risks/concerns exist for using Crux in a production environment? 

Thanks

**Comment by refset** [comment]
Hi Erik,

As it happens we are currently aiming for the next release tag to switch to using `-beta`, which is a big milestone in our beta programme. For context: https://www.opencrux.com/support. Drop me an email if you would like to be included in the formal beta discussions - it's certainly not too late! jdt@juxt.pro

The GA release will follow as soon as all of the beta feedback has been received and addressed. We expect this beta process will continue over the next 3-4 months.

On the general topic of stability, it is worth noting that we already have several production users who we are collaborating with to minimise disruption as we continue to work on the APIs and underlying index improvements. In terms of data integrity, assuming you already have a robust Kafka or JDBC storage option available to host the main logs, the risks of adopting Crux in production right now are very minimal. Our test suites are extensive and we perform nightly builds and bench runs against `master`.

One potential area of concern, where we don't yet provide any generic tooling to support you with today, is exactly how you should manage zero-downtime rolling upgrades - with multiple versions of Crux nodes reading & writing in parallel. This is something we hope to address with a higher-level cluster management capability, using k8s or otherwise. It is undoubtedly solvable in any case, without direct input from our end, but it deserves attention and an official solution in the near future.

It's fair to say that there is likely to be more churn across the APIs at this point (Java, HTTP and Clojure), but the basic data model, Datalog syntax and transaction operations are essentially already stable.

Please do get in touch directly if you have specific requirements to share or questions about the precise timing and content of the roadmap (k8s, JSON, SQL etc.) as I would be happy to dive into more detail. Otherwise though, feel free to continue discussions within this issue.

Thanks for asking :)
